import AppKit
import Foundation

/// Exports meeting debriefs as formatted markdown files.
final class ExportEngine {

    /// Export a single meeting debrief to markdown
    static func exportDebrief(meeting: Meeting) -> String {
        var md = "# \(meeting.title)\n\n"
        md += "**Date:** \(String(meeting.createdAt.prefix(10)))\n"
        md += "**Attendees:** \(meeting.attendeesFormatted)\n"
        md += "**Generated by:** RevyD\n\n"
        md += "---\n\n"

        if let summary = meeting.summaryMarkdown, !summary.isEmpty {
            md += "## Summary\n\n\(summary)\n\n"
        }

        // Parse debrief JSON if available
        if let debriefJson = meeting.debriefJson,
           let data = debriefJson.data(using: .utf8),
           let debrief = try? JSONDecoder().decode(DebriefResult.self, from: data) {

            if let summary = debrief.summary {
                md += "## Debrief\n\n\(summary)\n\n"
            }

            if let decisions = debrief.decisions, !decisions.isEmpty {
                md += "## Decisions\n\n"
                for d in decisions {
                    md += "- **\(d.description)**"
                    if let ctx = d.context { md += " — \(ctx)" }
                    md += "\n"
                }
                md += "\n"
            }

            if let actions = debrief.action_items, !actions.isEmpty {
                md += "## Action Items\n\n"
                md += "| Owner | Action | Due |\n|-------|--------|-----|\n"
                for a in actions {
                    md += "| \(a.owner) | \(a.description) | \(a.due_date ?? "—") |\n"
                }
                md += "\n"
            }

            if let given = debrief.commitments_given, !given.isEmpty {
                md += "## Commitments Given\n\n"
                for c in given {
                    md += "- **\(c.by)** → \(c.to ?? "team"): \(c.description)\n"
                    if let quote = c.source_quote { md += "  > \(quote)\n" }
                }
                md += "\n"
            }

            if let received = debrief.commitments_received, !received.isEmpty {
                md += "## Commitments Received\n\n"
                for c in received {
                    md += "- **\(c.by)** → \(c.to ?? "me"): \(c.description)\n"
                }
                md += "\n"
            }

            if let questions = debrief.open_questions, !questions.isEmpty {
                md += "## Open Questions\n\n"
                for q in questions { md += "- \(q)\n" }
                md += "\n"
            }

            if let topics = debrief.follow_up_topics, !topics.isEmpty {
                md += "## Follow-up Topics\n\n"
                for t in topics { md += "- \(t)\n" }
                md += "\n"
            }
        }

        if let notes = meeting.notesMarkdown, !notes.isEmpty {
            md += "## Meeting Notes\n\n\(notes)\n\n"
        }

        md += "---\n*Exported by RevyD on \(ISO8601DateFormatter().string(from: Date()))*\n"
        return md
    }

    /// Export and save to file with save dialog
    static func exportAndSave(meeting: Meeting) {
        let markdown = exportDebrief(meeting: meeting)
        let safeName = meeting.title
            .replacingOccurrences(of: "/", with: "-")
            .replacingOccurrences(of: ":", with: "-")
        let fileName = "\(safeName) — Debrief.md"

        let panel = NSSavePanel()
        panel.nameFieldStringValue = fileName
        panel.allowedContentTypes = [.text]
        panel.level = NSWindow.Level(rawValue: NSWindow.Level.statusBar.rawValue + 20)

        NSApp.activate(ignoringOtherApps: true)
        if panel.runModal() == .OK, let url = panel.url {
            try? markdown.write(to: url, atomically: true, encoding: .utf8)
        }
    }

    /// Export weekly digest as markdown
    static func exportWeeklyDigest() -> String {
        let store = MeetingStore()
        let commitmentStore = CommitmentStore()
        let personStore = PersonStore()

        let calendar = Calendar.current
        let weekAgo = calendar.date(byAdding: .day, value: -7, to: Date())!
        let weekAgoStr = ISO8601DateFormatter().string(from: weekAgo)

        // Get this week's meetings
        let allMeetings = store.getAll(limit: 500)
        let weekMeetings = allMeetings.filter { $0.createdAt >= weekAgoStr }

        let open = commitmentStore.getOpen()
        let overdue = commitmentStore.getOverdue()

        var md = "# Weekly Digest\n\n"
        md += "**Period:** \(String(weekAgoStr.prefix(10))) to \(String(ISO8601DateFormatter().string(from: Date()).prefix(10)))\n\n"
        md += "---\n\n"

        md += "## Overview\n\n"
        md += "- **\(weekMeetings.count)** meetings this week\n"
        md += "- **\(open.count)** open commitments\n"
        md += "- **\(overdue.count)** overdue\n"
        md += "- **\(personStore.count())** people in your network\n\n"

        if !weekMeetings.isEmpty {
            md += "## Meetings This Week\n\n"
            for m in weekMeetings {
                md += "### \(m.title) (\(String(m.createdAt.prefix(10))))\n"
                md += "Attendees: \(m.attendeesFormatted)\n"
                if let summary = m.summaryMarkdown { md += "\(String(summary.prefix(300)))\n" }
                md += "\n"
            }
        }

        if !overdue.isEmpty {
            md += "## Overdue Commitments\n\n"
            for c in overdue {
                md += "- **\(c.ownerName)**: \(c.description)"
                if let due = c.dueDate { md += " (due: \(String(due.prefix(10))))" }
                md += "\n"
            }
            md += "\n"
        }

        if !open.isEmpty {
            md += "## Open Commitments\n\n"
            for c in open.prefix(20) {
                md += "- \(c.ownerName): \(c.description)\n"
            }
        }

        md += "\n---\n*Generated by RevyD on \(String(ISO8601DateFormatter().string(from: Date()).prefix(10)))*\n"
        return md
    }
}
